name: ShiftPath
version: 1.9.8-DEVELOPMENT-SNAPSHOT
main: com.gmail.gogobebe2.shiftpath.ShiftPath
description: Make a path that shifts around.
author: William Bryant (gogobebe2)
website: gogobebe2@gmail.com
commands:
  shiftpath:
    description: Create plateforms of 2, 3 or 4 size and set a path they go through.
    aliases: [sp]