name: ShiftPath
version: 1.0.0-DEVELOPMENT-SNAPSHOT
main: com.gmail.gogobebe2.shiftpath.ShiftPath
description: Make a path that shifts around.
author: William Bryant (gogobebe2)
website: gogobebe2@gmail.com