name: ShiftPath
version: 1.0.1-PREALPHA-SNAPSHOT
main: com.gmail.gogobebe2.shiftpath.ShiftPath
description: Make a path that shifts around.
author: William Bryant (gogobebe2)
website: gogobebe2@gmail.com
commands:
  shiftpath:
    description: Part of Shift minigame. Allows the ability to create and set paths of defined platforms.
    aliases: [sp]
permissions:
  shiftpath.*:
    default: op
